import { Entities, IRepositories, Models } from '../../../domain';
import { Result } from '../../../domain/models';
import { GraphQLClient } from '../graphqlClient';
import { CHANGE_ORDER_STATUS, GET_INVOICE, UPDATE_ORDER_DYNAMIC_PROPERTIES } from './documents';

export class OrderRepository extends IRepositories.IEntityBaseRepository implements IRepositories.IOrderRepository {
  private _restClient = (this._context as GraphQLClient)._restContext;
  constructor(
    context: IRepositories.IClient,
    storeId?: string,
    catalogId?: string,
    cultureName?: string,
    currencyCode?: string,
    userId?: string,
    apiKey?: string,
  ) {
    super(context, storeId, catalogId, cultureName, currencyCode, userId, apiKey);
  }

  getInvoice = (number?: string, id?: string): Promise<Result<Partial<Entities.CustomerOrderType>>> => {
    return this._restClient
      .get<any>({
        segmentPath: id ? `api/order/customerOrders/${id}` : `api/order/customerOrders/number/${number}`,
        headers: {
          api_key: this.apiKey,
        },
      })
      .then(result => {
        if (result.error) {
          return {
            error: {
              code: 'OrderRepository.getInvoice',
              message: result.error?.message,
              trace: [result.error],
            },
          } as Models.Result<Partial<Entities.CustomerOrderType>>;
        } else {
          const order = result.data;

          const invoice: Partial<Entities.CustomerOrderType> = {
            status: order.status,
            createdDate: order.createdDate,
            customerId: order.customerId,
            feeTotal: order.feeTotal,
            feeTotalWithTax: order.feeTotalWithTax,
            feeWithTax: order.feeWithTax,
            id: order.id,
            isApproved: order.isApproved,
            isCancelled: order.isCancelled,
            isPrototype: order.isPrototype,
            number: order.number,
            objectType: order.objectType,
            operationType: order.operationType,
            storeId: order.storeId,
            taxPercentRate: order.taxPercentRate,
            discountTotalWithTax: {
              amount: (order.discountTotalWithTax ?? 0).toString(),
              decimalDigits: (order.discountTotalWithTax ?? 0).toString(),
              formattedAmount: (order.discountTotalWithTax ?? 0).toString() + ' ' + order.currency,
              formattedAmountWithoutCurrency: (order.discountTotalWithTax ?? 0).toString(),
              formattedAmountWithoutPoint: (order.discountTotalWithTax ?? 0).toString(),
              formattedAmountWithoutPointAndCurrency: (order.discountTotalWithTax ?? 0).toString(),
            },
            shippingTotal: {
              amount: (order.shippingTotal ?? 0).toString(),
              decimalDigits: (order.shippingTotal ?? 0).toString(),
              formattedAmount: (order.shippingTotal ?? 0).toString() + ' ' + order.currency,
              formattedAmountWithoutCurrency: (order.shippingTotal ?? 0).toString(),
              formattedAmountWithoutPoint: (order.shippingTotal ?? 0).toString(),
              formattedAmountWithoutPointAndCurrency: (order.shippingTotal ?? 0).toString(),
            },
            taxTotal: {
              amount: (order.taxTotal ?? 0).toString(),
              decimalDigits: (order.taxTotal ?? 0).toString(),
              formattedAmount: (order.taxTotal ?? 0).toString() + ' ' + order.currency,
              formattedAmountWithoutCurrency: (order.taxTotal ?? 0).toString(),
              formattedAmountWithoutPoint: (order.taxTotal ?? 0).toString(),
              formattedAmountWithoutPointAndCurrency: (order.taxTotal ?? 0).toString(),
            },
            subTotal: {
              amount: (order.subTotal ?? 0).toString(),
              decimalDigits: (order.subTotal ?? 0).toString(),
              formattedAmount: (order.subTotal ?? 0).toString() + ' ' + order.currency,
              formattedAmountWithoutCurrency: (order.subTotal ?? 0).toString(),
              formattedAmountWithoutPoint: (order.subTotal ?? 0).toString(),
              formattedAmountWithoutPointAndCurrency: (order.subTotal ?? 0).toString(),
            },
            total: {
              amount: (order.total ?? 0).toString(),
              decimalDigits: (order.total ?? 0).toString(),
              formattedAmount: (order.total ?? 0).toString() + ' ' + order.currency,
              formattedAmountWithoutCurrency: (order.total ?? 0).toString(),
              formattedAmountWithoutPoint: (order.total ?? 0).toString(),
              formattedAmountWithoutPointAndCurrency: (order.total ?? 0).toString(),
            },
            inPayments: [
              {
                gatewayCode: order.inPayments?.at(0)?.gatewayCode,
                createdDate: order.createdDate,
                customerId: order.customerId,
                id: order.inPayments?.at(0)?.id,
                isApproved: order.inPayments?.at(0).isApproved,
                isCancelled: order.inPayments?.at(0).isCancelled,
                number: order.inPayments?.at(0).number,
                objectType: order.inPayments?.at(0).objectType,
                operationType: order.inPayments?.at(0).operationType,
                order,
              },
            ],
            items: order.items?.map((x: any) => ({
              ...x,
              name: x.name,
              quantity: x.quantity,
              imageUrl: x.imageUrl,
              product: {
                id: x.productId,
                slug: 'NA',
              },
              placedPrice: {
                amount: x.price ?? 0,
                decimalDigits: x.price ?? 0,
                formattedAmount: (x.price ?? 0).toString() + ' ' + x.currency,
                formattedAmountWithoutCurrency: (x.price ?? 0).toString(),
                formattedAmountWithoutPoint: (x.price ?? 0).toString(),
                formattedAmountWithoutPointAndCurrency: (x.price ?? 0).toString(),
              },
              discountAmount: {
                amount: x.discountAmount ?? 0,
                decimalDigits: x.discountAmount ?? 0,
                formattedAmount: (x.discountAmount ?? 0).toString() + ' ' + x.currency,
                formattedAmountWithoutCurrency: (x.discountAmount ?? 0).toString(),
                formattedAmountWithoutPoint: (x.discountAmount ?? 0).toString(),
                formattedAmountWithoutPointAndCurrency: (x.discountAmount ?? 0).toString(),
              },
              extendedPrice: {
                amount: x.extendedPrice ?? 0,
                decimalDigits: x.extendedPrice ?? 0,
                formattedAmount: (x.extendedPrice ?? 0).toString() + ' ' + x.currency,
                formattedAmountWithoutCurrency: (x.extendedPrice ?? 0).toString(),
                formattedAmountWithoutPoint: (x.extendedPrice ?? 0).toString(),
                formattedAmountWithoutPointAndCurrency: (x.extendedPrice ?? 0).toString(),
              },
              taxTotal: {
                amount: (x.taxTotal ?? 0).toString(),
                decimalDigits: (x.taxTotal ?? 0).toString(),
                formattedAmount: (x.taxTotal ?? 0).toString() + ' ' + x.currency,
                formattedAmountWithoutCurrency: (x.taxTotal ?? 0).toString(),
                formattedAmountWithoutPoint: (x.taxTotal ?? 0).toString(),
                formattedAmountWithoutPointAndCurrency: (x.taxTotal ?? 0).toString(),
              },
            })),
            shipments: order.shipments?.map((x: any) => ({
              deliveryAddress: x.deliveryAddress,
            })),
            discountTotal: {
              amount: order.discountTotal ?? 0,
              decimalDigits: order.discountTotal ?? 0,
              formattedAmount: (order.discountTotal ?? 0).toString() + ' ' + order.currency,
              formattedAmountWithoutCurrency: (order.discountTotal ?? 0).toString(),
              formattedAmountWithoutPoint: (order.discountTotal ?? 0).toString(),
              formattedAmountWithoutPointAndCurrency: (order.discountTotal ?? 0).toString(),
            },
            shippingSubTotalWithTax: {
              amount: order.shippingSubTotalWithTax ?? 0,
              decimalDigits: order.shippingSubTotalWithTax ?? 0,
              formattedAmount: (order.shippingSubTotalWithTax ?? 0).toString() + ' ' + order.currency,
              formattedAmountWithoutCurrency: (order.shippingSubTotalWithTax ?? 0).toString(),
              formattedAmountWithoutPoint: (order.shippingSubTotalWithTax ?? 0).toString(),
              formattedAmountWithoutPointAndCurrency: (order.shippingSubTotalWithTax ?? 0).toString(),
            },
          };
          // console.log({ invoice: JSON.stringify(invoice) });
          return { data: invoice } as Models.Result<Partial<Entities.CustomerOrderType>>;
        }
      })
      .catch(
        exp =>
          ({
            error: {
              code: 'OrderRepository.getInvoice',
              message: exp.message,
              exception: exp,
            },
          }) as Models.Result<Partial<Entities.CustomerOrderType>>,
      );
  };

  changeOrderStatus = (status: string, orderId: string): Promise<Models.Result<boolean>> => {
    return this._context
      .post<Required<Pick<Entities.Mutations, 'changeOrderStatus'>>, Entities.InputChangeOrderStatusType>({
        mutation: CHANGE_ORDER_STATUS,
        variables: {
          command: {
            orderId,
            status,
          },
        },
      })
      .then(result => {
        if (result.error) {
          return {
            error: {
              code: 'OrderRepository.changeOrderStatus',
              message: result.error?.message,
              trace: [result.error],
            },
          } as Models.Result<boolean>;
        } else {
          return {
            data: result.data?.changeOrderStatus,
          } as Models.Result<boolean>;
        }
      });
  };

  updateOrderDynamicProperties = (
    name: string,
    value: string,
    orderId: string,
  ): Promise<Models.Result<Partial<Entities.CustomerOrderType>>> => {
    return this._context
      .post<
        Required<Pick<Entities.Mutations, 'updateOrderDynamicProperties'>>,
        Entities.InputUpdateOrderDynamicPropertiesType
      >({
        mutation: UPDATE_ORDER_DYNAMIC_PROPERTIES,
        variables: {
          command: {
            orderId,
            dynamicProperties: [{ name, value, cultureName: this.cultureName }],
          },
        },
      })
      .then(result => {
        if (result.error) {
          return {
            error: {
              code: 'OrderRepository.updateOrderDynamicProperties',
              message: result.error?.message,
              trace: [result.error],
            },
          } as Models.Result<Partial<Entities.CustomerOrderType>>;
        } else {
          return {
            data: result.data?.updateOrderDynamicProperties,
          } as Models.Result<Partial<Entities.CustomerOrderType>>;
        }
      });
  };
}
/*
{
    "rowVersion": "AAAAAAABsgs=",
    "customerId": "807f96cb-e276-44a3-85d7-6b85ef23408b",
    "customerName": "Mohamed Farag",
    "channelId": null,
    "storeId": "alkhbaz",
    "storeName": null,
    "organizationId": null,
    "organizationName": null,
    "employeeId": null,
    "employeeName": null,
    "shoppingCartId": "8913e142-136d-473d-ba8f-49a0f2ca868a",
    "isPrototype": false,
    "purchaseOrderNumber": null,
    "subscriptionNumber": null,
    "subscriptionId": null,
    "objectType": "TotPlatform.OrdersModule.Core.Model.CustomerOrder",
    "addresses": [
        {
            "addressType": "Billing",
            "key": "d53c3582-7189-44a9-915d-21364ed303ee",
            "name": null,
            "organization": null,
            "countryCode": "EGY",
            "countryName": "Egypt",
            "city": "6044",
            "postalCode": "6044",
            "zip": null,
            "line1": "Masaken Al Dobbat,building:48,floor:5,apt:21",
            "line2": null,
            "regionId": "604",
            "regionName": "مصر الجديدة",
            "firstName": "Mohamed",
            "middleName": null,
            "lastName": "Ibrahim",
            "phone": "+201111166549",
            "email": "e.mohammedfarag@gmail.com",
            "outerId": null,
            "isDefault": false,
            "description": null
        }
    ],
    "inPayments": [
        {
            "orderId": "4ace2df3-b0b2-48f8-b591-e3e033631451",
            "purpose": null,
            "gatewayCode": "DefaultManualPaymentMethod",
            "paymentMethod": {
                "paymentMethodType": "Unknown",
                "paymentMethodGroupType": "Manual",
                "code": "DefaultManualPaymentMethod",
                "name": "Test payment method",
                "logoUrl": null,
                "isActive": true,
                "priority": 0,
                "isAvailableForPartial": false,
                "allowDeferredPayment": false,
                "currency": null,
                "price": 0.0,
                "priceWithTax": 0.0,
                "total": 0.0,
                "totalWithTax": 0.0,
                "discountAmount": 0.0,
                "discountAmountWithTax": 0.0,
                "storeId": "alkhbaz",
                "description": "Cash on Delivery",
                "typeName": "DefaultManualPaymentMethod",
                "settings": [
                    {
                        "itHasValues": false,
                        "objectId": "0f004f88-1095-415a-a2d0-8472ef9f20fb",
                        "objectType": "DefaultManualPaymentMethod",
                        "isReadOnly": false,
                        "value": null,
                        "id": null,
                        "restartRequired": false,
                        "moduleId": "TotPlatform.Payment",
                        "groupName": "Payment|DefaultManualPaymentMethod",
                        "name": "TotPlatform.Payment.DefaultManualPaymentMethod.ExampleSetting",
                        "displayName": null,
                        "isRequired": false,
                        "isHidden": false,
                        "valueType": "ShortText",
                        "allowedValues": null,
                        "defaultValue": null,
                        "isDictionary": false
                    }
                ],
                "taxType": null,
                "taxTotal": 0.0,
                "taxPercentRate": 0.0,
                "taxDetails": null,
                "id": "0f004f88-1095-415a-a2d0-8472ef9f20fb"
            },
            "organizationId": null,
            "organizationName": null,
            "customerId": "807f96cb-e276-44a3-85d7-6b85ef23408b",
            "customerName": null,
            "incomingDate": null,
            "billingAddress": {
                "addressType": "Billing",
                "key": "3e9f758f-e79c-4b31-939b-5b6db075d591",
                "name": null,
                "organization": null,
                "countryCode": "EGY",
                "countryName": "Egypt",
                "city": "6044",
                "postalCode": "6044",
                "zip": null,
                "line1": "Masaken Al Dobbat,building:48,floor:5,apt:21",
                "line2": null,
                "regionId": "604",
                "regionName": "مصر الجديدة",
                "firstName": "Mohamed",
                "middleName": null,
                "lastName": "Ibrahim",
                "phone": "+201111166549",
                "email": "e.mohammedfarag@gmail.com",
                "outerId": null,
                "isDefault": false,
                "description": null
            },
            "paymentStatus": "New",
            "authorizedDate": null,
            "capturedDate": null,
            "voidedDate": null,
            "processPaymentResult": null,
            "price": 0.0000,
            "priceWithTax": 0.00000000,
            "total": 0.0000,
            "totalWithTax": 0.00000000,
            "discountAmount": 0.0000,
            "discountAmountWithTax": 0.00000000,
            "objectType": "TotPlatform.OrdersModule.Core.Model.PaymentIn",
            "feeDetails": [],
            "vendorId": null,
            "taxType": null,
            "taxTotal": 0.00000000,
            "taxPercentRate": 0.0000,
            "taxDetails": [],
            "discounts": [],
            "transactions": [],
            "refunds": [],
            "captures": [],
            "operationType": "PaymentIn",
            "parentOperationId": null,
            "number": "PI240307-00009",
            "isApproved": false,
            "status": "New",
            "comment": null,
            "currency": "EGP",
            "sum": 51.0000,
            "outerId": "3de4fbe5d7d64920",
            "childrenOperations": [],
            "cancelledState": "Undefined",
            "isCancelled": false,
            "cancelledDate": null,
            "cancelReason": null,
            "dynamicProperties": [],
            "operationsLog": null,
            "createdDate": "2024-03-07T16:45:22.0635308Z",
            "modifiedDate": "2024-03-07T21:17:27.928048Z",
            "createdBy": "mohammed.farag@totplatform.com",
            "modifiedBy": "mohammed.farag@totplatform.com",
            "id": "7ff081c2-74d7-4f7a-81f8-060c49edaf6b"
        }
    ],
    "items": [
        {
            "priceId": "83f0eea5-fccb-4420-a88d-19eb7aab8096",
            "currency": "EGP",
            "price": 20.0000,
            "priceWithTax": 21.00000000,
            "placedPrice": 20.0000,
            "placedPriceWithTax": 21.00000000,
            "extendedPrice": 20.0000,
            "extendedPriceWithTax": 21.00000000,
            "discountAmount": 0.0000,
            "discountAmountWithTax": 0.00000000,
            "discountTotal": 0.0000,
            "discountTotalWithTax": 0.00000000,
            "fee": 0.0000,
            "feeWithTax": 0.00000000,
            "taxType": "5",
            "taxTotal": 1.00000000,
            "taxPercentRate": 0.0500,
            "reserveQuantity": 0,
            "quantity": 1,
            "productId": "5217",
            "sku": "5217",
            "productType": "Physical",
            "catalogId": "0a841b7e-c732-4738-913d-9e43c054170e",
            "categoryId": "111009000000",
            "name": "كب كيك فواكه  مسكره",
            "comment": null,
            "status": null,
            "imageUrl": "https://dev.alkhbaz.totplatform.net/assets/catalog/0a841/5217/5217.jpg",
            "isGift": false,
            "shippingMethodCode": null,
            "fulfillmentLocationCode": null,
            "fulfillmentCenterId": "140302000000",
            "fulfillmentCenterName": "التجمع",
            "outerId": null,
            "feeDetails": [],
            "vendorId": null,
            "weightUnit": null,
            "weight": null,
            "measureUnit": null,
            "height": null,
            "length": null,
            "width": null,
            "isCancelled": false,
            "cancelledDate": null,
            "cancelReason": null,
            "objectType": "TotPlatform.OrdersModule.Core.Model.LineItem",
            "dynamicProperties": [],
            "discounts": [],
            "taxDetails": [],
            "createdDate": "2024-03-07T16:45:22.0635808Z",
            "modifiedDate": "2024-03-07T16:45:22.0635808Z",
            "createdBy": "mohammed.farag@totplatform.com",
            "modifiedBy": "mohammed.farag@totplatform.com",
            "id": "19cea840-8306-493a-bfcf-4f7113680db8"
        }
    ],
    "shipments": [
        {
            "organizationId": null,
            "organizationName": null,
            "fulfillmentCenterId": "140203000000",
            "fulfillmentCenterName": null,
            "employeeId": null,
            "employeeName": null,
            "shipmentMethodCode": "ZoneRate",
            "shipmentMethodOption": null,
            "shippingMethod": {
                "code": "ZoneRate",
                "name": "Zone Shipping Rate",
                "description": null,
                "logoUrl": null,
                "isActive": true,
                "priority": 0,
                "taxType": null,
                "storeId": "alkhbaz",
                "settings": null,
                "typeName": "ZoneShippingMethod",
                "id": "db69a5c3-57cc-4b6d-be21-53c460e7d44a"
            },
            "customerOrderId": "4ace2df3-b0b2-48f8-b591-e3e033631451",
            "customerOrder": null,
            "items": [],
            "packages": [],
            "inPayments": [],
            "feeDetails": [],
            "weightUnit": null,
            "weight": null,
            "measureUnit": null,
            "height": null,
            "length": null,
            "width": null,
            "discounts": [],
            "deliveryAddress": {
                "addressType": "Billing",
                "key": "5995ef02-1f1c-42ad-b996-c5184de78eaa",
                "name": null,
                "organization": null,
                "countryCode": "EGY",
                "countryName": "Egypt",
                "city": "6044",
                "postalCode": "6044",
                "zip": null,
                "line1": "Masaken Al Dobbat,building:48,floor:5,apt:21",
                "line2": null,
                "regionId": "604",
                "regionName": "مصر الجديدة",
                "firstName": "Mohamed",
                "middleName": null,
                "lastName": "Ibrahim",
                "phone": "+201111166549",
                "email": "e.mohammedfarag@gmail.com",
                "outerId": null,
                "isDefault": false,
                "description": null
            },
            "price": 30.0000,
            "priceWithTax": 30.00000000,
            "total": 30.0000,
            "totalWithTax": 30.00000000,
            "discountAmount": 0.0000,
            "discountAmountWithTax": 0.00000000,
            "fee": 0.0000,
            "feeWithTax": 0.00000000,
            "trackingNumber": null,
            "trackingUrl": null,
            "deliveryDate": null,
            "objectType": "TotPlatform.OrdersModule.Core.Model.Shipment",
            "vendorId": null,
            "taxType": null,
            "taxTotal": 0.00000000,
            "taxPercentRate": 0.0000,
            "taxDetails": [],
            "operationType": "Shipment",
            "parentOperationId": null,
            "number": "SH240307-00009",
            "isApproved": false,
            "status": "New",
            "comment": null,
            "currency": "EGP",
            "sum": 30.0000,
            "outerId": null,
            "childrenOperations": [],
            "cancelledState": "Undefined",
            "isCancelled": false,
            "cancelledDate": null,
            "cancelReason": null,
            "dynamicProperties": [],
            "operationsLog": null,
            "createdDate": "2024-03-07T16:45:22.0637993Z",
            "modifiedDate": "2024-03-07T16:45:22.0637993Z",
            "createdBy": "mohammed.farag@totplatform.com",
            "modifiedBy": "mohammed.farag@totplatform.com",
            "id": "1e40b1ca-4c28-4618-9388-c3c052c8e1ff"
        }
    ],
    "feeDetails": [],
    "discounts": [],
    "discountAmount": 0.0000,
    "taxDetails": [],
    "scopes": null,
    "total": 51.00,
    "subTotal": 20.00,
    "subTotalWithTax": 21.00,
    "subTotalDiscount": 0.00,
    "subTotalDiscountWithTax": 0.00,
    "subTotalTaxTotal": 1.00000000,
    "shippingTotal": 30.00,
    "shippingTotalWithTax": 30.00,
    "shippingSubTotal": 30.00,
    "shippingSubTotalWithTax": 30.00,
    "shippingDiscountTotal": 0.0000,
    "shippingDiscountTotalWithTax": 0.00000000,
    "shippingTaxTotal": 0.0,
    "paymentTotal": 0.00,
    "paymentTotalWithTax": 0.00,
    "paymentSubTotal": 0.00,
    "paymentSubTotalWithTax": 0.00,
    "paymentDiscountTotal": 0.00,
    "paymentDiscountTotalWithTax": 0.00,
    "paymentTaxTotal": 0.0,
    "discountTotal": 0.00,
    "discountTotalWithTax": 0.00,
    "fee": 0.00,
    "feeWithTax": 0.00,
    "feeTotal": 0.00,
    "feeTotalWithTax": 0.00,
    "handlingTotal": 0.0000,
    "handlingTotalWithTax": 0.0000,
    "taxType": null,
    "taxTotal": 1.00,
    "taxPercentRate": 0.0500,
    "languageCode": "en-US",
    "operationType": "CustomerOrder",
    "parentOperationId": null,
    "number": "INV240307-00009",
    "isApproved": true,
    "status": "Processing",
    "comment": null,
    "currency": "EGP",
    "sum": 51.00,
    "outerId": null,
    "childrenOperations": [
        {
            "orderId": "4ace2df3-b0b2-48f8-b591-e3e033631451",
            "purpose": null,
            "gatewayCode": "DefaultManualPaymentMethod",
            "paymentMethod": {
                "paymentMethodType": "Unknown",
                "paymentMethodGroupType": "Manual",
                "code": "DefaultManualPaymentMethod",
                "name": "Test payment method",
                "logoUrl": null,
                "isActive": true,
                "priority": 0,
                "isAvailableForPartial": false,
                "allowDeferredPayment": false,
                "currency": null,
                "price": 0.0,
                "priceWithTax": 0.0,
                "total": 0.0,
                "totalWithTax": 0.0,
                "discountAmount": 0.0,
                "discountAmountWithTax": 0.0,
                "storeId": "alkhbaz",
                "description": "Cash on Delivery",
                "typeName": "DefaultManualPaymentMethod",
                "settings": [
                    {
                        "itHasValues": false,
                        "objectId": "0f004f88-1095-415a-a2d0-8472ef9f20fb",
                        "objectType": "DefaultManualPaymentMethod",
                        "isReadOnly": false,
                        "value": null,
                        "id": null,
                        "restartRequired": false,
                        "moduleId": "TotPlatform.Payment",
                        "groupName": "Payment|DefaultManualPaymentMethod",
                        "name": "TotPlatform.Payment.DefaultManualPaymentMethod.ExampleSetting",
                        "displayName": null,
                        "isRequired": false,
                        "isHidden": false,
                        "valueType": "ShortText",
                        "allowedValues": null,
                        "defaultValue": null,
                        "isDictionary": false
                    }
                ],
                "taxType": null,
                "taxTotal": 0.0,
                "taxPercentRate": 0.0,
                "taxDetails": null,
                "id": "0f004f88-1095-415a-a2d0-8472ef9f20fb"
            },
            "organizationId": null,
            "organizationName": null,
            "customerId": "807f96cb-e276-44a3-85d7-6b85ef23408b",
            "customerName": null,
            "incomingDate": null,
            "billingAddress": {
                "addressType": "Billing",
                "key": "3e9f758f-e79c-4b31-939b-5b6db075d591",
                "name": null,
                "organization": null,
                "countryCode": "EGY",
                "countryName": "Egypt",
                "city": "6044",
                "postalCode": "6044",
                "zip": null,
                "line1": "Masaken Al Dobbat,building:48,floor:5,apt:21",
                "line2": null,
                "regionId": "604",
                "regionName": "مصر الجديدة",
                "firstName": "Mohamed",
                "middleName": null,
                "lastName": "Ibrahim",
                "phone": "+201111166549",
                "email": "e.mohammedfarag@gmail.com",
                "outerId": null,
                "isDefault": false,
                "description": null
            },
            "paymentStatus": "New",
            "authorizedDate": null,
            "capturedDate": null,
            "voidedDate": null,
            "processPaymentResult": null,
            "price": 0.0000,
            "priceWithTax": 0.00000000,
            "total": 0.0000,
            "totalWithTax": 0.00000000,
            "discountAmount": 0.0000,
            "discountAmountWithTax": 0.00000000,
            "objectType": "TotPlatform.OrdersModule.Core.Model.PaymentIn",
            "feeDetails": [],
            "vendorId": null,
            "taxType": null,
            "taxTotal": 0.00000000,
            "taxPercentRate": 0.0000,
            "taxDetails": [],
            "discounts": [],
            "transactions": [],
            "refunds": [],
            "captures": [],
            "operationType": "PaymentIn",
            "parentOperationId": null,
            "number": "PI240307-00009",
            "isApproved": false,
            "status": "New",
            "comment": null,
            "currency": "EGP",
            "sum": 51.0000,
            "outerId": "3de4fbe5d7d64920",
            "childrenOperations": [],
            "cancelledState": "Undefined",
            "isCancelled": false,
            "cancelledDate": null,
            "cancelReason": null,
            "dynamicProperties": [],
            "operationsLog": null,
            "createdDate": "2024-03-07T16:45:22.0635308Z",
            "modifiedDate": "2024-03-07T21:17:27.928048Z",
            "createdBy": "mohammed.farag@totplatform.com",
            "modifiedBy": "mohammed.farag@totplatform.com",
            "id": "7ff081c2-74d7-4f7a-81f8-060c49edaf6b"
        },
        {
            "organizationId": null,
            "organizationName": null,
            "fulfillmentCenterId": "140203000000",
            "fulfillmentCenterName": null,
            "employeeId": null,
            "employeeName": null,
            "shipmentMethodCode": "ZoneRate",
            "shipmentMethodOption": null,
            "shippingMethod": {
                "code": "ZoneRate",
                "name": "Zone Shipping Rate",
                "description": null,
                "logoUrl": null,
                "isActive": true,
                "priority": 0,
                "taxType": null,
                "storeId": "alkhbaz",
                "settings": null,
                "typeName": "ZoneShippingMethod",
                "id": "db69a5c3-57cc-4b6d-be21-53c460e7d44a"
            },
            "customerOrderId": "4ace2df3-b0b2-48f8-b591-e3e033631451",
            "customerOrder": null,
            "items": [],
            "packages": [],
            "inPayments": [],
            "feeDetails": [],
            "weightUnit": null,
            "weight": null,
            "measureUnit": null,
            "height": null,
            "length": null,
            "width": null,
            "discounts": [],
            "deliveryAddress": {
                "addressType": "Billing",
                "key": "5995ef02-1f1c-42ad-b996-c5184de78eaa",
                "name": null,
                "organization": null,
                "countryCode": "EGY",
                "countryName": "Egypt",
                "city": "6044",
                "postalCode": "6044",
                "zip": null,
                "line1": "Masaken Al Dobbat,building:48,floor:5,apt:21",
                "line2": null,
                "regionId": "604",
                "regionName": "مصر الجديدة",
                "firstName": "Mohamed",
                "middleName": null,
                "lastName": "Ibrahim",
                "phone": "+201111166549",
                "email": "e.mohammedfarag@gmail.com",
                "outerId": null,
                "isDefault": false,
                "description": null
            },
            "price": 30.0000,
            "priceWithTax": 30.00000000,
            "total": 30.0000,
            "totalWithTax": 30.00000000,
            "discountAmount": 0.0000,
            "discountAmountWithTax": 0.00000000,
            "fee": 0.0000,
            "feeWithTax": 0.00000000,
            "trackingNumber": null,
            "trackingUrl": null,
            "deliveryDate": null,
            "objectType": "TotPlatform.OrdersModule.Core.Model.Shipment",
            "vendorId": null,
            "taxType": null,
            "taxTotal": 0.00000000,
            "taxPercentRate": 0.0000,
            "taxDetails": [],
            "operationType": "Shipment",
            "parentOperationId": null,
            "number": "SH240307-00009",
            "isApproved": false,
            "status": "New",
            "comment": null,
            "currency": "EGP",
            "sum": 30.0000,
            "outerId": null,
            "childrenOperations": [],
            "cancelledState": "Undefined",
            "isCancelled": false,
            "cancelledDate": null,
            "cancelReason": null,
            "dynamicProperties": [],
            "operationsLog": null,
            "createdDate": "2024-03-07T16:45:22.0637993Z",
            "modifiedDate": "2024-03-07T16:45:22.0637993Z",
            "createdBy": "mohammed.farag@totplatform.com",
            "modifiedBy": "mohammed.farag@totplatform.com",
            "id": "1e40b1ca-4c28-4618-9388-c3c052c8e1ff"
        }
    ],
    "cancelledState": "Undefined",
    "isCancelled": false,
    "cancelledDate": null,
    "cancelReason": null,
    "dynamicProperties": [],
    "operationsLog": null,
    "createdDate": "2024-03-07T16:45:22.0633994Z",
    "modifiedDate": "2024-03-07T21:17:27.9274057Z",
    "createdBy": "mohammed.farag@totplatform.com",
    "modifiedBy": "admin",
    "id": "4ace2df3-b0b2-48f8-b591-e3e033631451"
}
*/
