export const PackagesData = [
  {
    type: 'Basic',
    recommended: false,
    countPerWeek: 50,
    servicesCount: 10,
    staffCount: 10,
    appointMent: '100 Appointment',
    gallery: false,
    additionServices: false,
  },
  {
    type: 'Business',
    recommended: true,
    countPerWeek: 200,
    servicesCount: 20,
    staffCount: 20,
    appointMent: 'Unlimited Appointment',
    gallery: false,
    additionServices: false,
  },
  {
    type: 'Enterprise',
    recommended: false,
    countPerWeek: 450,
    servicesCount: 10,
    staffCount: 10,
    appointMent: '100 Appointment',
    gallery: true,
    additionServices: true,
  },
];
